version: 2.1

workflows:
  test:
    jobs:
      - prep-deps
      - lint:
          requires:
            - prep-deps
      - test-10:
          requires:
            - prep-deps
      - test-12:
          requires:
            - prep-deps
      - test-14:
          requires:
            - prep-deps
      - test-browser:
          requires:
            - prep-deps


jobs:
  prep-deps:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            .circleci/scripts/deps-install.sh
      - run:
          name: Collect yarn install HAR logs
          command: |
            .circleci/scripts/collect-har-artifact.sh
      - persist_to_workspace:
          root: .
          paths:
          - node_modules
          - build-artifacts

  lint:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint

  test-browser:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Unit tests
          command: yarn test:browser


  test-10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Unit tests
          command: yarn test

  test-12:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Unit tests
          command: yarn test

  test-14:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Unit tests
          command: yarn test
